"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$r*pf@k$pbajx&!)s@#mphi29$(fnwervx#^93@78mppk@l=t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Autenticación
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tu aplicación modular de SUNAT
    'facturacion',
    # Documentación API (Swagger) — rúbrica docente
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <-- Le dice a Django que busque aquí tus HTML
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'facturacion.context_processors.layout_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_facturacion',
        'USER': 'postgres',
        'PASSWORD': 'sunat_secure_pass',
        'HOST': 'localhost',
        'PORT': '5433', # El puerto seguro que asignamos para no colisionar
    }
}

# Tests unitarios sin depender de PostgreSQL local
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test_db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde Django buscará los archivos estáticos en desarrollo
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ── Facturación electrónica / SUNAT ───────────────────────────────────────────
IGV_PORCENTAJE = 0.18

# beta = envío real SOAP a SUNAT | simulado = solo si SUNAT_MODO=simulado (tests)
SUNAT_MODO = os.environ.get('SUNAT_MODO', 'beta')

# Certificado digital (.pfx en core/certs/ o certs/)
_pfx_default = BASE_DIR / 'core' / 'certs' / 'DEMO_Sunat.pfx'
if not _pfx_default.is_file():
    for _carpeta in (BASE_DIR / 'core' / 'certs', BASE_DIR / 'certs'):
        if _carpeta.is_dir():
            _archivos = list(_carpeta.glob('*.pfx'))
            if _archivos:
                _pfx_default = _archivos[0]
                break
SUNAT_CERT_PATH = os.environ.get('SUNAT_CERT_PATH') or str(_pfx_default.resolve())
SUNAT_CERT_PASSWORD = os.environ.get('SUNAT_CERT_PASSWORD', 'Jhonain321')
# RUC del certificado DEMO_Sunat.pfx (debe coincidir con el emisor en el XML)
SUNAT_CERT_RUC = os.environ.get('SUNAT_CERT_RUC', '20100066603')
SUNAT_USUARIO_SOL = os.environ.get('SUNAT_USUARIO_SOL', 'MODDATOS')
SUNAT_CLAVE_SOL = os.environ.get('SUNAT_CLAVE_SOL', 'MODDATOS')
SUNAT_URL_BETA = 'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService'

MEDIA_ROOT = BASE_DIR / 'storage'
XML_FIRMADOS_DIR = MEDIA_ROOT / 'xmls' / 'firmados'
CDRS_DIR = MEDIA_ROOT / 'xmls' / 'cdrs'

for _sunat_dir in (XML_FIRMADOS_DIR, CDRS_DIR):
    os.makedirs(_sunat_dir, exist_ok=True)

# ── OpenAPI / Swagger (drf-spectacular) ───────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Facturación Electrónica SUNAT',
    'DESCRIPTION': (
        'Endpoints del sistema de facturación electrónica (UBL 2.1). '
        'Incluye emisión de comprobantes, búsqueda y consulta.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'name': 'Equipo Facturación Electrónica'},
}