"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$r*pf@k$pbajx&!)s@#mphi29$(fnwervx#^93@78mppk@l=t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # Tu aplicación modular de SUNAT
    'facturacion',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'core.middleware.AuthRedirectMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <-- Le dice a Django que busque aquí tus HTML
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde Django buscará los archivos estáticos en desarrollo
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Tu porcentaje de IGV
IGV_PORCENTAJE = 0.18

# Rutas físicas donde tu backend guardará los XMLs creados
MEDIA_ROOT = BASE_DIR / 'storage'
XML_FIRMADOS_DIR = MEDIA_ROOT / 'xmls' / 'firmados'
XML_FIRMADOS_DIR     = MEDIA_ROOT / 'pdfs'
CDRS_DIR             = MEDIA_ROOT / 'cdrs'

# Crear los directorios automáticamente si no existen al levantar tu servidor
import os
if not os.path.exists(XML_FIRMADOS_DIR):
    os.makedirs(XML_FIRMADOS_DIR, exist_ok=True)

# Certificado digital 
SUNAT_CERT_PATH      = BASE_DIR / config('SUNAT_CERT_PATH', default='certs/DEMO_Sunat.pfx')
SUNAT_CERT_PASSWORD  = config('SUNAT_CERT_PASSWORD', default='')
SUNAT_CERT_RUC       = config('SUNAT_CERT_RUC', default='')

# SUNAT 
SUNAT_URL_BETA       = config('SUNAT_URL_BETA')
SUNAT_USUARIO_SOL    = config('SUNAT_USUARIO_SOL', default='MODDATOS')
SUNAT_CLAVE_SOL      = config('SUNAT_CLAVE_SOL', default='moddatos')