# Generated by Django 6.0.5 on 2026-05-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nrodoc', models.CharField(max_length=15)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id_emisor', models.AutoField(primary_key=True, serialize=False)),
                ('tipodoc', models.CharField(max_length=1)),
                ('ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('usuario_sol', models.CharField(max_length=20)),
                ('clave_sol', models.CharField(max_length=20)),
                ('porcetajeigv', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                'db_table': 'emisor',
            },
        ),
        migrations.CreateModel(
            name='EnvioResumen',
            fields=[
                ('id_envio_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('fecha_referencia', models.DateField()),
                ('correlativo', models.IntegerField()),
                ('resumen', models.SmallIntegerField()),
                ('baja', models.SmallIntegerField()),
                ('nombrexml', models.CharField(max_length=50)),
                ('mensaje_sunat', models.CharField(max_length=20)),
                ('codigo_sunat', models.CharField(max_length=20)),
                ('ticket', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'envio_resumen',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('codigo_sunat', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.IntegerField()),
            ],
            options={
                'db_table': 'serie',
            },
        ),
        migrations.CreateModel(
            name='TipoAfectacion',
            fields=[
                ('id_tipo_afectacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=3)),
                ('tipo', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'tipo_afectacion',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id_tipo_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_comprobante',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('op_grabadas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('op_exoneradas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('op_inefactas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo_comprobante_ref_id', models.CharField(blank=True, max_length=4, null=True)),
                ('serie_ref', models.CharField(blank=True, max_length=4, null=True)),
                ('correlativo_ref', models.IntegerField(blank=True, null=True)),
                ('codmotivo', models.CharField(blank=True, max_length=5, null=True)),
                ('nombrexml', models.CharField(blank=True, max_length=50, null=True)),
                ('xmlbase64', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('cdrbase64', models.TextField(blank=True, null=True)),
                ('codigo_sunat', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje_sunat', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_comprobante', models.CharField(blank=True, max_length=1, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='facturacion.cliente')),
                ('id_emisor', models.ForeignKey(db_column='id_emisor', on_delete=django.db.models.deletion.PROTECT, to='facturacion.emisor')),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.PROTECT, to='facturacion.moneda')),
                ('id_serie', models.ForeignKey(db_column='id_serie', on_delete=django.db.models.deletion.PROTECT, to='facturacion.serie')),
                ('id_tipo_comprobante', models.ForeignKey(db_column='id_tipo_comprobante', on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante')),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=3, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('id_comprobante', models.ForeignKey(db_column='id_comprobante', on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobante')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
        migrations.CreateModel(
            name='EnvioResumenDetalle',
            fields=[
                ('id_resumen_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('condicion', models.SmallIntegerField()),
                ('id_comprobante', models.ForeignKey(db_column='id_comprobante', on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobante')),
                ('id_envio_resumen', models.ForeignKey(db_column='id_envio_resumen', on_delete=django.db.models.deletion.CASCADE, to='facturacion.envioresumen')),
            ],
            options={
                'db_table': 'envio_resumen_detalle',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=15)),
                ('igv', models.DecimalField(decimal_places=6, max_digits=15)),
                ('porcentaje_igv', models.DecimalField(decimal_places=6, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=6, max_digits=15)),
                ('importe_total', models.DecimalField(decimal_places=6, max_digits=15)),
                ('id_comprobante', models.ForeignKey(db_column='id_comprobante', on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobante')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto')),
            ],
            options={
                'db_table': 'detalle',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_afectacion',
            field=models.ForeignKey(db_column='id_tipo_afectacion', on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoafectacion'),
        ),
        migrations.AddField(
            model_name='serie',
            name='id_tipo_comprobante',
            field=models.ForeignKey(db_column='id_tipo_comprobante', on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_doc',
            field=models.ForeignKey(db_column='id_tipo_doc', on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_unidad',
            field=models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.PROTECT, to='facturacion.unidad'),
        ),
    ]
