from decimal import Decimal


TIPO_FACTURA = "01"
TIPO_BOLETA = "03"
TIPO_NOTA_CREDITO = "07"
TIPO_NOTA_DEBITO = "08"

TIPOS_COMPROBANTE = (
    (TIPO_FACTURA, "Factura"),
    (TIPO_BOLETA, "Boleta"),
    (TIPO_NOTA_CREDITO, "Nota de Credito"),
    (TIPO_NOTA_DEBITO, "Nota de Debito"),
)

TIPO_DOC_SIN_DOCUMENTO = "0"
TIPO_DOC_DNI = "1"
TIPO_DOC_CARNET_EXTRANJERIA = "4"
TIPO_DOC_RUC = "6"
TIPO_DOC_PASAPORTE = "7"

TIPOS_DOCUMENTO_IDENTIDAD = (
    (TIPO_DOC_SIN_DOCUMENTO, "Sin documento"),
    (TIPO_DOC_DNI, "DNI"),
    (TIPO_DOC_CARNET_EXTRANJERIA, "Carnet extranjeria"),
    (TIPO_DOC_RUC, "RUC"),
    (TIPO_DOC_PASAPORTE, "Pasaporte"),
)

ESTADO_BORRADOR = "BORRADOR"
ESTADO_GENERADO = "GENERADO"
ESTADO_FIRMADO = "FIRMADO"
ESTADO_ENVIADO = "ENVIADO"
ESTADO_ACEPTADO = "ACEPTADO"
ESTADO_RECHAZADO = "RECHAZADO"
ESTADO_ERROR = "ERROR"
ESTADO_ANULADO = "ANULADO"

ESTADOS_COMPROBANTE = (
    (ESTADO_BORRADOR, "Borrador"),
    (ESTADO_GENERADO, "Generado"),
    (ESTADO_FIRMADO, "Firmado"),
    (ESTADO_ENVIADO, "Enviado"),
    (ESTADO_ACEPTADO, "Aceptado"),
    (ESTADO_RECHAZADO, "Rechazado"),
    (ESTADO_ERROR, "Error"),
    (ESTADO_ANULADO, "Anulado"),
)

MONEDA_PEN = "PEN"
IGV_RATE = Decimal("0.18")
AFECTACION_GRAVADO = "10"
UNIDAD_NIU = "NIU"
TRIBUTO_IGV = "1000"
SUNAT_DEMO_RUC = "20100066603"
